### ISSUE TITLE
Delete All option inside local Mailboxes

### ISSUE THREAD

**Issue by TechTailor** [beyondcode/helo-laravel#9]
As the title suggest, an option to delete all the emails inside a local mailbox. Right now I can only find the option to delete each email one-by-one, so a quick option to delete all of them would be a nice addition.

**Comment by mpociot** [comment]
You can right click on a mailbox in the list and delete the complete mailbox :)

**Comment by TechTailor** [comment]
Thats the first thing I tried, getting nothing on right click. Right clicking on the sidebar menu is just giving the option to Copy Link. Mailbox itself is not giving any option.

**Comment by jahhernandez** [comment]
Sorry to post here, but I cannot find a way to delete the entire mailbox by right clicking the mailbox neither on Windows nor Linux.
I included here what happens if I try it.
I also tried on multiple computers with the same result. The right click does not shows up.

![jzVuZBfRDp](https://user-images.githubusercontent.com/16142755/94513661-49163080-01ed-11eb-9344-c325a2ac7e69.gif)

**Comment by sschlein** [comment]
1.2 will be released this week and has an additional option to do this right to the share icon

**Comment by jahhernandez** [comment]
> 1.2 will be released this week and has an additional option to do this right to the share icon

Thanks for the quick reply!

**Comment by TechTailor** [comment]
Oh the right click shows up after you open the mailbox. So open the mail box, when you see all the emails, right-click on the mail-box name and you will get the option to delete it.

**Comment by jahhernandez** [comment]
> Oh the right click shows up after you open the mailbox. So open the mail box, when you see all the emails, right-click on the mail-box name (above the Back button) and you will get the option to delete it.

Yes! now it works, also the new version is out!
